IF
	StateCheck(Myself,STATE_PANIC)
THEN
	RESPONSE #100
		RandomWalkContinuous()
END

IF
	Allegiance(Myself,ENEMY)
	See([PC])
	!Range(LastSeenBy(Myself),4)
	CanEquipRanged()
THEN
	RESPONSE #100
		EquipRanged()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Allegiance(Myself,ENEMY)
	See([PC])
	OR(2)
		Range(LastSeenBy(Myself),4)
		!CanEquipRanged()
THEN
	RESPONSE #100
		EquipRanged()
		AttackReevaluate(LastSeenBy(Myself),45)
END

