IF
	StateCheck(Myself,STATE_PANIC)
THEN
	RESPONSE #100
		RandomWalkContinuous()
END

IF
	See([GOODCUTOFF.0.0.0.250]) //240
	CanEquipRanged()
	!Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #100
		EquipRanged()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	See([GOODCUTOFF.0.0.0.250]) //240
	OR(2)
		Range(LastSeenBy(Myself),3)
		!CanEquipRanged()
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

