IF
	!Global("TEAM_9","MYAREA",1)
	OR(2)
		AttackedBy([GOODCUTOFF],DEFAULT)
		PickPocketFailed([PC])
THEN
	RESPONSE #100
		SetGlobal("TEAM_9","MYAREA",1)
		Continue()
END

/*IF
	!IsTeamBitOn(TEAM_9_BIT)
THEN
	RESPONSE #100
		SetTeamBit(TEAM_9_BIT,TRUE)
		Continue()
END*/

IF
	!Global("TEAM_9","MYAREA",1)
	Allegiance(Myself,ENEMY)
	IsActive(Myself)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobal("TEAM_9","MYAREA",1)
		Continue()
END

