IF
	!Global("TEAM_17","MYAREA",1)
	OR(2)
		AttackedBy([GOODCUTOFF],DEFAULT)
		PickPocketFailed([PC])
THEN
	RESPONSE #100
		SetGlobal("TEAM_17","MYAREA",1)
		Continue()
END

/*IF
	!IsTeamBitOn(TEAM_17_BIT)
THEN
	RESPONSE #100
		SetTeamBit(TEAM_17_BIT,TRUE)
		Continue()
END*/

IF
	!Global("TEAM_17","MYAREA",1)
	Allegiance(Myself,ENEMY)
	IsActive(Myself)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobal("TEAM_17","MYAREA",1)
		Continue()
END

