IF
	Global("I_LIKE_DWARVES","LOCALS",0)
	See([PC])
THEN
	RESPONSE #75
		SetGlobal("I_LIKE_DWARVES","LOCALS",2)
		Continue()
	RESPONSE #25
		SetGlobal("I_LIKE_DWARVES","LOCALS",1)
		Continue()
END

IF
	StateCheck(Myself,STATE_PANIC)
THEN
	RESPONSE #100
		RandomWalkContinuous()
END

IF
	Global("I_LIKE_DWARVES","LOCALS",1)
	OR(2)
		See([0.0.DWARF])
		See([PC.0.DWARF])
	CanEquipRanged()
	!Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #100
		EquipRanged()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	Global("I_LIKE_DWARVES","LOCALS",1)
	OR(2)
		See([0.0.DWARF])
		See([PC.0.DWARF])
	OR(2)
	  Range(LastSeenBy(Myself),3)
	  !CanEquipRanged()
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END
/* Old_OR
IF
	OR(9)
		See(NearestEnemyOf(Myself))
		See("HEDRON")
		See("JORUN")
		See("CRANDALL")
		See("BROGAN")
		See("JON")
		See("REIG")
		See("SCREED")
		See("ELDGULL")
	CanEquipRanged()
	!Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #100
		EquipRanged()
		AttackReevaluate(LastSeenBy(Myself),45)
END*/

/*IF
	See("HEDRON")
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	CanEquipRanged()
	!Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #40
		EquipRanged()
		AttackReevaluate(LastSeenBy(Myself),45)
	RESPONSE #60
		Continue()
END

IF
	See("JORUN")
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	CanEquipRanged()
	!Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #40
		EquipRanged()
		AttackReevaluate(LastSeenBy(Myself),45)
	RESPONSE #60
		Continue()
END

IF
	See("CRANDALL")
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	CanEquipRanged()
	!Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #40
		EquipRanged()
		AttackReevaluate(LastSeenBy(Myself),45)
	RESPONSE #60
		Continue()
END

IF
	See("BROGAN")
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	CanEquipRanged()
	!Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #40
		EquipRanged()
		AttackReevaluate(LastSeenBy(Myself),45)
	RESPONSE #60
		Continue()
END

IF
	See("JON")
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	CanEquipRanged()
	!Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #40
		EquipRanged()
		AttackReevaluate(LastSeenBy(Myself),45)
	RESPONSE #60
		Continue()
END

IF
	See("REIG")
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	CanEquipRanged()
	!Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #40
		EquipRanged()
		AttackReevaluate(LastSeenBy(Myself),45)
	RESPONSE #60
		Continue()
END

IF
	See("SCREED")
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	CanEquipRanged()
	!Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #40
		EquipRanged()
		AttackReevaluate(LastSeenBy(Myself),45)
	RESPONSE #60
		Continue()
END

IF
	See("ELDGULL")
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	CanEquipRanged()
	!Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #40
		EquipRanged()
		AttackReevaluate(LastSeenBy(Myself),45)
	RESPONSE #60
		Continue()
END*/

IF
	OR(9)
		See("ELDGULL")
		See("SCREED")
		See("REIG")
		See("JON")
		See("BROGAN")
		See("CRANDALL")
		See("JORUN")
		See("HEDRON")
		See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	CanEquipRanged()
	!Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #100
		EquipRanged()
		AttackReevaluate(LastSeenBy(Myself),45)
END

/*Old_OR
IF
	OR(9)
		See(NearestEnemyOf(Myself))
		See("HEDRON")
		See("JORUN")
		See("CRANDALL")
		See("BROGAN")
		See("JON")
		See("REIG")
		See("SCREED")
		See("ELDGULL")
	OR(2)
	  Range(LastSeenBy(Myself),3)
	  !CanEquipRanged()
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END*/

/*IF
	See("HEDRON")
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	OR(2)
	  Range(LastSeenBy(Myself),3)
	  !CanEquipRanged()
THEN
	RESPONSE #40
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
	RESPONSE #60
		Continue()
END

IF
	See("JORUN")
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	OR(2)
	  Range(LastSeenBy(Myself),3)
	  !CanEquipRanged()
THEN
	RESPONSE #40
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
	RESPONSE #60
		Continue()
END

IF
	See("CRANDALL")
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	OR(2)
	  Range(LastSeenBy(Myself),3)
	  !CanEquipRanged()
THEN
	RESPONSE #40
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
	RESPONSE #60
		Continue()
END

IF
	See("BROGAN")
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	OR(2)
	  Range(LastSeenBy(Myself),3)
	  !CanEquipRanged()
THEN
	RESPONSE #40
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
	RESPONSE #60
		Continue()
END

IF
	See("JON")
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	OR(2)
	  Range(LastSeenBy(Myself),3)
	  !CanEquipRanged()
THEN
	RESPONSE #40
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
	RESPONSE #60
		Continue()
END

IF
	See("REIG")
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	OR(2)
	  Range(LastSeenBy(Myself),3)
	  !CanEquipRanged()
THEN
	RESPONSE #40
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
	RESPONSE #60
		Continue()
END

IF
	See("SCREED")
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	OR(2)
	  Range(LastSeenBy(Myself),3)
	  !CanEquipRanged()
THEN
	RESPONSE #40
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
	RESPONSE #60
		Continue()
END

IF
	See("ELDGULL")
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	OR(2)
	  Range(LastSeenBy(Myself),3)
	  !CanEquipRanged()
THEN
	RESPONSE #40
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
	RESPONSE #60
		Continue()
END*/

IF
	OR(9)
		See("ELDGULL")
		See("SCREED")
		See("REIG")
		See("JON")
		See("BROGAN")
		See("CRANDALL")
		See("JORUN")
		See("HEDRON")
		See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	OR(2)
	  Range(LastSeenBy(Myself),3)
	  !CanEquipRanged()
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

