IF
	OR(2)
		Dead("Braston")
		GlobalGT("SPRITE_IS_DEADBraston","GLOBAL",0)
THEN
	RESPONSE #100
		DestroySelf()
END

/*IF
	!CreatureHidden(Myself)
THEN
	RESPONSE #100
		HideCreature(Myself,TRUE)
		Continue()
END*/

IF
	Global("30BRASTO_ESCAPE","GLOBAL",2)
	Global("BRASTON_PAUSED_STATE","GLOBAL",0)
	See("Braston")
THEN
	RESPONSE #100
		IncrementGlobal("30BRASTO_ESCAPE","GLOBAL",1)
		SetGlobal("BRASTON_PAUSED_STATE","GLOBAL",2)
		ClearActions("Braston")
		DisplayStringHead("Braston",@32047)
END

