IF
	Clicked([ANYONE])
	!Range(LastTrigger,5)
THEN
	RESPONSE #100
		SetGlobal("FireKeyClick","MYAREA",1)
		ActionOverride(LastTrigger,MoveToPoint([2688.1472]))
END

IF
	OR(2)
		Clicked([ANYONE])
		Global("FireKeyClick","MYAREA",1)
	Range(LastTrigger,5)
THEN
	RESPONSE #100
		ForceSpellRES("IWWI417",LastTrigger)  // WIZARD_BELTYNS_BURNING_BLOOD
		OpenDoor("AR4100_Door13")
		SetGlobal("TEAM_3","MYAREA",1)
		TriggerActivation("FireKey",FALSE)
		//ChangeCurrentScript("")
END

