IF
	GlobalTimerNotExpired("PrismFireDelay","MYAREA")
THEN
	RESPONSE #100
		NoAction()
END

IF
	Global("41PrismTarget","MYAREA",1)
THEN
	RESPONSE #100
		ForceSpellPointRES("IWWI092",[940.326])
		TriggerActivation(Myself,FALSE)
END

IF
	Global("41PrismTarget","MYAREA",2)
THEN
	RESPONSE #100
		ForceSpellPointRES("IWWI092",[502.766])
		SetGlobalTimer("PrismFireDelay","MYAREA",1)
		TriggerActivation("Mirror9",TRUE)
		TriggerActivation(Myself,FALSE)
END

