IF
	GlobalTimerNotExpired("PrismFireDelay","MYAREA")
THEN
	RESPONSE #100
		NoAction()
END

IF
	Global("41PrismFire","MYAREA",3)
	Global("PrismSequence","MYAREA",3)
THEN
	RESPONSE #100
		ForceSpellPointRES("IWWI092",[2350.1119])
		TriggerActivation(Myself,FALSE)
END

IF
	Global("41PrismFire","MYAREA",3)
	Global("PrismSequence","MYAREA",7)
THEN
	RESPONSE #100
		ForceSpellPointRES("IWWI092",[2360.1439])
		TriggerActivation("Mirror18",TRUE)
		TriggerActivation(Myself,FALSE)
END

