IF
	Global("41PrismFire","MYAREA",3)
	OpenState("AR4102_Door15",TRUE)
THEN
	RESPONSE #100
		ForceSpellPointRES("IWWI092",[1059.2516])
		SetGlobalTimer("PrismFireDelay","MYAREA",2)
		TriggerActivation("Mirror4",TRUE)
		TriggerActivation(Myself,FALSE)
END

IF
	Global("41PrismFire","MYAREA",3)
	OpenState("AR4102_Door15",FALSE)
THEN
	RESPONSE #100
		ForceSpellPointRES("IWWI092",[1059.2516])
		TriggerActivation(Myself,FALSE)
END

