IF
	Global("SORDI_CALL_FOR_BACKUP","MYAREA",0)
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		FaceObject(LastSeenBy(Myself))
		DisplayStringHead(Myself,@17021)
		SetGlobal("SORDI_CALL_FOR_BACKUP","MYAREA",1)
		Continue()
END

IF
	Global("50Wight_Horn","GLOBAL",2)
THEN
	RESPONSE #100
		UseItem("z1veira2",Myself)
		Wait(1)
		DestroySelf()
END

IF
	AttackedBy([GOODCUTOFF],DEFAULT)
THEN
	RESPONSE #100
		Enemy()
END

