IF
	Global("WATCHING_PLAYER","MYAREA",0)
	//!CreatureHidden(Myself)
	!StateCheck(Myself,STATE_NOT_VISIBLE)
THEN
	RESPONSE #100
		//SetCreatureAreaFlag(Myself,IGNORE_AI_INHIBIT,TRUE)
		ApplySpellRES("IWPERAI",Myself)
		//SpellHitEffectSprite(Myself,Myself,DEATH_SPELL,10)
		CreateVisualEffectObject("DSPELLH",Myself)
		Wait(1)
		DestroySelf()
END

IF
	Global("WATCHING_PLAYER","MYAREA",0)
	//CreatureHidden(Myself)
	StateCheck(Myself,STATE_NOT_VISIBLE)
THEN
	RESPONSE #100
		DestroySelf()
END

