IF
	StateCheck(Myself,STATE_PANIC)
THEN
	RESPONSE #100
		RandomWalkContinuous()
END

IF
	OR(5)
		See("6051Heartless_Dead1")
		See("6051Heartless_Dead6")
		See("6051Heartless_Dead7")
		See("6051Heartless_Dead8")
		See(NearestEnemyOf(Myself))
		//See("6051Heartless_Dead5",0)
		//See("6051Heartless_Dead4",0)
		//See("6051Heartless_Dead3",0)
		//See("6051Heartless_Dead2",0)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

