IF
	Global("ar6051_Kill_FireAndAcid","GLOBAL",1)
THEN
	RESPONSE #100
		NoAction()
		Wait(3000)
END

IF
	Disarmed([ANYONE])
THEN
	RESPONSE #100
		SetGlobal("Fire_Room_Active","MYAREA",-1)
		CloseDoor(Myself)
		SetGlobal("Fire_Room_Armed","MYAREA",-1)
		CloseDoor("AR6051_Lava_Art")
		DisplayString(LastTrigger,@37446)
END

IF
	Closed([ANYONE])
THEN
	RESPONSE #100
		SetGlobal("Fire_Room_Active","MYAREA",11)
END

