IF
	!GlobalTimerNotExpired("60TRFB01_TIMER","MYAREA")
	OpenState("AR6051_Blades1",TRUE)
THEN
	RESPONSE #100
		CloseDoor("AR6051_Blades1")
		SetGlobalTimer("60TRFB01_TIMER","MYAREA",3)
END

IF
	!GlobalTimerNotExpired("60TRFB01_TIMER","MYAREA")
	Entered([PC])
THEN
	RESPONSE #100
		OpenDoor("AR6051_Blades1")
		ForceSpellRES("IWIN249",LastTrigger)  // SPIN249.SPL TRAP_FLOOR_BLADES
		DisplayString(LastTrigger,14381)
		SetGlobalTimer("60TRFB01_TIMER","MYAREA",3)
END

