IF
	True()
THEN
	RESPONSE #100
		CutSceneId("Saablic_Tan")
		MultiPlayerSync()
		Wait(1)
		ForceSpellPoint([1405.1070],WIZARD_DIMENSION_DOOR)
		Wait(3)
		//DestroySelf()
		
		MultiPlayerSync()
		
		EndCutSceneMode()
		//MultiPlayerSync()
		DestroySelf()
END

IF
	True()
THEN
	RESPONSE #100
		CutSceneId("Wanmok")
		MultiPlayerSync()
		Wait(2)
		ForceSpellPoint([1405.1070],WIZARD_DIMENSION_DOOR)
		Wait(1)
		DestroySelf()
END

