IF
	StateCheck(Myself,STATE_PANIC)
THEN
	RESPONSE #100
		RandomWalkContinuous()
END

IF
	OR(2)
		See([ENEMY.UNDEAD.ELF])
		See(NearestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),4)
	CanEquipRanged()
THEN
	RESPONSE #100
		EquipRanged()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	OR(2)
		See([ENEMY.UNDEAD.ELF])
		See(NearestEnemyOf(Myself))
	OR(2)
		Range(LastSeenBy(Myself),4)
		!CanEquipRanged()
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

